### ISSUE TITLE
References credits

### ISSUE THREAD

**Issue by moonflower0000** [MarcosNicolau/obsidian-for-academia#2]
I'd like to write the references of my article in a single column, but the rest of article I'm writing in two columns. But I tried so many and it seems pretty impossible to write the references in one column. Any suggestion? is there even possible?

**Comment by MarcosNicolau** [comment]
Hi @moonflower0000 ,

I never really tried that, tbh since I mostly use pandoc when exporting my notes to PDFs. Though, this is nothing you could not handle with some css. I guess, you could wrap the bibliography in a callout, remove all its styling, and add the property `column-span: all` to the callout container so that it spans across all the columns.

**Comment by moonflower0000** [comment]
I'll try that. I'm actually pretty new on this CSS stuff, but thank you

**Comment by MarcosNicolau** [comment]
You are welcome :)
